
apiVersion: v1
kind: Secret
metadata:
 creationTimestamp: null
 name: powervs-credentials
 namespace: openshift-machine-api
stringData:
 ibm-credentials.env: |-
  IBMCLOUD_AUTHTYPE=iam
  IBMCLOUD_APIKEY=${ADMIN_IBMCLOUD_API_KEY}
 ibmcloud_api_key: ${ADMIN_IBMCLOUD_API_KEY}
type: Opaque

apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: ibm-cloud-credentials
  namespace: openshift-cloud-controller-manager
stringData:
  ibm-credentials.env: |-
    IBMCLOUD_AUTHTYPE=iam
    IBMCLOUD_APIKEY=${ADMIN_IBMCLOUD_API_KEY}
  ibmcloud_api_key: ${ADMIN_IBMCLOUD_API_KEY}
type: Opaque

apiVersion: v1
kind: Secret
metadata:
 creationTimestamp: null
 name: cloud-credentials
 namespace: openshift-ingress-operator
stringData:
 ibm-credentials.env: |-
  IBMCLOUD_AUTHTYPE=iam
  IBMCLOUD_APIKEY=${ADMIN_IBMCLOUD_API_KEY}
 ibmcloud_api_key: ${ADMIN_IBMCLOUD_API_KEY}
type: Opaque
